name: equidock
channels:
  - defaults
  - dglteam/label/th24_cu124
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - dgl=2.4.0.th24.cu124
  - expat=2.7.3
  - idna=3.11
  - intel-openmp=2025.0.0
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - numpy-base=2.2.5
  - openssl=3.0.18
  - pip=25.2
  - psutil=7.0.0
  - pthread-stubs=0.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - readline=8.3
  - requests=2.32.5
  - scipy=1.15.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tqdm=4.67.1
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - biopandas==0.5.1
      - cloudpickle==3.1.2
      - dgllife==0.3.2
      - filelock==3.20.0
      - fsspec==2025.10.0
      - future==1.0.0
      - hyperopt==0.2.7
      - jinja2==3.1.6
      - joblib==1.5.2
      - looseversion==1.1.2
      - markupsafe==3.0.3
      - mmtf-python==1.1.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.4.99
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pot==0.9.6.post1
      - py4j==0.10.9.9
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdkit==2025.9.1
      - scikit-learn==1.7.2
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.4.0+cu124
      - torchaudio==2.4.0+cu124
      - torchvision==0.19.0+cu124
      - triton==3.0.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
